### ISSUE TITLE
Question regarding database implementation.

### ISSUE THREAD

**Issue by krlicmuhamed** [jsumners/njs-di-example#1]
Hello, awesome example I've learned a lot!

I was wondering how would you implement a database component and Its query result functions?

This is how I would do it:

I would make a component that returns a database connection and another component that requires database component that includes a callback function that selects something from a database and returns results.
Then in a third component ( or should I say main component ) I would require that second component and call It's callback functions that return db results.

Is that a good practice/design pattern? [I've tried to do It here](https://github.com/jaredhanson/electrolyte/issues/17)

Thanks :+1:

**Comment by jsumners** [comment]
Thank you. I'm glad it has helped.

I have created a new branch 'db-example'. This branch shows how to create a database connection pool object that can be required using the Electrolyte injection mechanisms.

https://github.com/jsumners/njs-di-example/tree/db-example
